#!/bin/bash
# push-to-github.sh - Auto-commit enriched stakeholder database
# Usage: ./push-to-github.sh "version_tag" "commit_message"

set -e

REPO_DIR="/tmp/Voron-Campaign"
SOURCE_CSV="/home/p62operator/.openclaw/workspace-hoi/voron-prospects/prospect-database-7stakeholders.csv"
GIT_EMAIL="p62operator@proton.me"
GIT_NAME="p62operator"
REPO_URL="https://github.com/ahmadfaurani/Voron-Campaign"

VERSION_TAG="${1:-v$(date +%Y%m%d-%H%M%S)}"
COMMIT_MSG="${2:-Stakeholder enrichment update}"

echo "=== VoronDRQ GitHub Auto-Push ==="
echo "Version: $VERSION_TAG"
echo "Commit Message: $COMMIT_MSG"
echo ""

# Clone or update repo
if [ -d "$REPO_DIR" ]; then
    echo "Updating existing repo..."
    cd "$REPO_DIR"
    git pull origin main
else
    echo "Cloning repo..."
    git clone "$REPO_URL" "$REPO_DIR"
    cd "$REPO_DIR"
fi

# Configure git
git config user.email "$GIT_EMAIL"
git config user.name "$GIT_NAME"

# Copy enriched database
echo "Copying stakeholder database..."
cp "$SOURCE_CSV" "$REPO_DIR/prospects/prospect-database-7stakeholders.csv"

# Check for changes
cd "$REPO_DIR"
git add prospects/prospect-database-7stakeholders.csv

if git diff --cached --quiet; then
    echo ""
    echo "✅ No changes to commit - database already up to date"
    echo "Commit: $(git rev-parse --short HEAD)"
    echo "URL: https://github.com/ahmadfaurani/Voron-Campaign/commit/$(git rev-parse HEAD)"
    exit 0
fi

# Commit and push
echo "Committing changes..."
git commit -m "[$VERSION_TAG] $COMMIT_MSG

Classification: TLP:AMBER
Auto-generated by VoronDRQ Stakeholder Collection Agent"

echo "Pushing to GitHub..."
git push origin main

# Output commit info
COMMIT_HASH=$(git rev-parse --short HEAD)
COMMIT_URL="https://github.com/ahmadfaurani/Voron-Campaign/commit/$(git rev-parse HEAD)"
RAW_CSV_URL="https://raw.githubusercontent.com/ahmadfaurani/Voron-Campaign/main/prospects/prospect-database-7stakeholders.csv"

echo ""
echo "✅ GitHub push successful!"
echo "📝 Commit: $COMMIT_HASH"
echo "🔗 Commit URL: $COMMIT_URL"
echo "📄 Raw CSV: $RAW_CSV_URL"
